name: Security Audit
on:
  pull_request:
    paths:
      - Cargo.lock
  push:
    branches:
      - main
    paths:
      - Cargo.lock
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo audit and save output
        run: cargo audit --json > audit.json

      - name: Upload audit result
        uses: actions/upload-artifact@v3
        with:
          name: cargo-audit-result
          path: audit.json
