name: Security Audit
on:
  pull_request:
    paths:
      - Cargo.lock
  push:
    branches:
      - main
    paths:
      - Cargo.lock
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Install cargo-sarif
        run: cargo install --git https://github.com/psastras/cargo-sarif

      - name: Run cargo audit and output SARIF
        run: |
          cargo audit --json > audit.json
          cargo sarif audit.json > audit.sarif
      
      - name: Upload SARIF file to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: audit.sarif
